(function(window) {
    "use strict";

    var exactTranslations = {
        "*may be difficult to distinguish cusps/leaflets in TTE image": "*在 TTE 图像中可能难以区分瓣尖/瓣叶",
        "*may not be seen in TTE image": "*TTE 图像中可能看不到",
        "*not often seen in TTE image": "*TTE 图像中不常见",
        "10-12cm to image the descending aorta": "10-12 cm，用于显示降主动脉",
        "10-14cm to see the entire LV and pericardium": "10-14 cm，用于显示整个左心室和心包",
        "10-16cm to see the ascending aorta in LAX": "10-16 cm，用于在长轴切面显示升主动脉",
        "10-16cm to see the descending aorta": "10-16 cm，用于显示降主动脉",
        "10-16cm to see the descending aorta in SAX": "10-16 cm，用于在短轴切面显示降主动脉",
        "10-16cm to see the entire LV": "10-16 cm，用于显示整个左心室",
        "10-16cm to see the IVC": "10-16 cm，用于显示下腔静脉",
        "10-16cm to see the PA bifurcation": "10-16 cm，用于显示肺动脉分叉",
        "14-18cm to image both atria": "14-18 cm，用于显示双心房",
        "14-18cm to image the atria": "14-18 cm，用于显示心房",
        "14-18cm to image the LA": "14-18 cm，用于显示左心房",
        "16-24cm to image the entire IVC": "16-24 cm，用于显示整个下腔静脉",
        "16-24cm to image the entire LA and LV": "16-24 cm，用于显示整个左心房和左心室",
        "16-24cm to image the entire LV": "16-24 cm，用于显示整个左心室",
        "16-24cm to image the entire RV": "16-24 cm，用于显示整个右心室",
        "6-10cm to assess the LV apex": "6-10 cm，用于评估左心室心尖",
        "a small portion of the RV apex may be seen": "可见少量右心室心尖",
        "Adjust the image gain to:": "调整图像增益：",
        "Adjust the sector depth to:": "调整扫查深度：",
        "Adjust the TTE probe position to:": "调整 TTE 探头位置：",
        "Anterior (A)": "前壁（A）",
        "Anterior Mitral Valve Leaflet (AMVL)": "二尖瓣前叶（AMVL）",
        "Anterior Tricuspid Valve leaflet (ATVL)": "三尖瓣前叶（ATVL）",
        "Anterior Tricuspid Valve Leaflet (ATVL)": "三尖瓣前叶（ATVL）",
        "Anterolateral (AL)": "前外侧壁（AL）",
        "Antero-lateral (AL)": "前外侧壁（AL）",
        "Anterolateral Papillary Muscle (AL)": "前外侧乳头肌（AL）",
        "Anteroseptal (AS)": "前间隔（AS）",
        "Antero-septal (AS)": "前间隔（AS）",
        "Anteroseptal (IVS)": "前间隔（IVS）",
        "Aorta": "主动脉",
        "Aorta: size, aneurysm and dissection": "主动脉：大小、动脉瘤和夹层",
        "Aorta: size, aneurysm, dissection": "主动脉：大小、动脉瘤、夹层",
        "Aortic root": "主动脉根部",
        "Aortic root: size, dilation and dissection": "主动脉根部：大小、扩张和夹层",
        "Aortic Valve": "主动脉瓣",
        "Aortic Valve (AV)": "主动脉瓣（AV）",
        "Aortic Valve (AV)*": "主动脉瓣（AV）*",
        "Aortic Valve: structure and function": "主动脉瓣：结构和功能",
        "Apex": "心尖",
        "Apical aneurysm": "心尖部室壁瘤",
        "Apical thrombus": "心尖部血栓",
        "Apical wall thickness (HOCM, non compaction)": "心尖壁厚度（肥厚型梗阻性心肌病、心肌致密化不全）",
        "Arch": "主动脉弓",
        "Ascending (Ao)": "升主动脉（Ao）",
        "Ascending (ASC)": "升主动脉（ASC）",
        "Ascending Aorta (Ao)": "升主动脉（Ao）",
        "Ascending Aorta(Ao)": "升主动脉（Ao）",
        "Ascending Aorta: aneurysm, dissection": "升主动脉：动脉瘤、夹层",
        "at the left parasternal border": "位于左胸骨旁缘",
        "at the right parasternal border": "位于右胸骨旁缘",
        "atria and IAS should be incompletely seen": "心房和房间隔应只显示部分",
        "Atrial septal defect": "房间隔缺损",
        "Atrial Septal Defect: Sinus Venosus Type": "房间隔缺损：静脉窦型",
        "AV and LVOT should not be seen (too much probe rotation)": "不应看到主动脉瓣和左室流出道（探头旋转过多）",
        "AV should not be seen only aorta (tilt probe superior)": "不应看到主动脉瓣，只显示主动脉（探头向上倾斜）",
        "Branching pulmonary artery": "肺动脉分支",
        "Cardiac motion during code blue": "抢救期间的心脏运动",
        "center the image (slide probe away from sternum)": "使图像居中（探头远离胸骨滑动）",
        "center the image (slide probe)": "使图像居中（滑动探头）",
        "change in IVC size with respiration": "下腔静脉随呼吸的直径变化",
        "Chiari network": "Chiari 网",
        "Coarctation of the aorta": "主动脉缩窄",
        "Coronary sinus": "冠状静脉窦",
        "Coronary Sinus (CS)": "冠状静脉窦（CS）",
        "Coronary sinus dilatation": "冠状静脉窦扩张",
        "Descending (DA)": "降主动脉（DA）",
        "Descending Aorta": "降主动脉",
        "Descending Aorta (DA)": "降主动脉（DA）",
        "Descending Aorta (DA)*": "降主动脉（DA）*",
        "Descending Aorta (DA): SAX and LAX": "降主动脉（DA）：短轴和长轴",
        "Descending aorta can be seen by tilting probe posterior and medial": "将探头向后内侧倾斜可显示降主动脉",
        "Descending aorta in LAX rotate probe clockwise": "长轴显示降主动脉时顺时针旋转探头",
        "Descending Aorta: aneurysm, dissection": "降主动脉：动脉瘤、夹层",
        "Differentiate the IVC from the aorta by:": "通过以下方式区分下腔静脉和主动脉：",
        "ensure all four cardiac chambers are seen": "确认四个心腔均可见",
        "ensure cardiac chambers are centered (slide probe lateral)": "确认心腔居中（探头向外侧滑动）",
        "ensure the LV apex is not seen (rotate probe)": "确认不显示左心室心尖（旋转探头）",
        "ensure the LV, LA and MV are seen": "确认可见左心室、左心房和二尖瓣",
        "flat and push down with a slight tilt to the patient's right": "探头平放并下压，稍向患者右侧倾斜",
        "Free (lateral) wall": "游离壁（侧壁）",
        "from the Apical 2 Chamber view, rotate 45 degrees counterclockwise and tilt anterior": "从心尖两腔心切面开始，逆时针旋转 45 度并向前倾斜",
        "from the Apical 4 Chamber view, rotate the probe 60-90 degrees counterclockwise": "从心尖四腔心切面开始，将探头逆时针旋转 60-90 度",
        "from the subcostal 4C view , rotate the probe 90° counterclockwise while keeping the RA in view": "从剑突下四腔心切面开始，在保持右心房可见的同时将探头逆时针旋转 90 度",
        "from the subcostal 4C view, rotate the probe the probe 90° counterclockwise": "从剑突下四腔心切面开始，将探头逆时针旋转 90 度",
        "Hepatic Vein (HV)": "肝静脉（HV）",
        "hepatic vein entering IVC": "肝静脉汇入下腔静脉",
        "if LV tilted to right (move probe laterally)": "如果左心室向右倾斜（探头向外侧移动）",
        "if LV tilted to right (slide probe lateral)": "如果左心室向右倾斜（探头向外侧滑动）",
        "if LV tilted to the left (move probe medially)": "如果左心室向左倾斜（探头向内侧移动）",
        "if LV tilted to the left (slide probe medial)": "如果左心室向左倾斜（探头向内侧滑动）",
        "if the atria are not seen, tilt the probe anterior": "如果看不到心房，将探头向前倾斜",
        "if the ventricles are too spherical, move probe down one interspace": "如果心室过于圆形，将探头下移一个肋间隙",
        "image an hepatic vein": "显示一支肝静脉",
        "in order of importance": "按重要性排序",
        "In order of importance": "按重要性排序",
        "In order of importance:": "按重要性排序：",
        "in the 2nd or 3rd intercostal space": "位于第 2 或第 3 肋间隙",
        "in the 3rd or 4th intercostal space": "位于第 3 或第 4 肋间隙",
        "in the 4th or 5th intercostal space": "位于第 4 或第 5 肋间隙",
        "in the midclavicular line or at the point of apical pulsation": "位于锁骨中线或心尖搏动最明显处",
        "in the subxiphoid region of the abdomen": "位于腹部剑突下区域",
        "in the suprasternal notch": "位于胸骨上窝",
        "increase to 20cm to assess the left pleural space": "增加至 20 cm，用于评估左侧胸膜腔",
        "Inferior (I or IVS)": "下壁（I 或 IVS）",
        "Inferior (I)": "下壁（I）",
        "Inferior Vena Cava (IVC)": "下腔静脉（IVC）",
        "Inferolateral (IL)": "下外侧壁（IL）",
        "Infero-lateral (IL)": "下外侧壁（IL）",
        "Inferoseptal (IS)": "下间隔（IS）",
        "Infero-septal (IS)": "下间隔（IS）",
        "Interatrial Septum (IAS)": "房间隔（IAS）",
        "Inter-atrial Septum (IAS)": "房间隔（IAS）",
        "Interolateral Papillary Muscle (AL)": "前外侧乳头肌（AL）",
        "Inter-ventricular Septum (IVS)": "室间隔（IVS）",
        "Interventricular Septum (IVS), infero-septal (IS)": "室间隔（IVS），下间隔（IS）",
        "Intra-cardiac mass": "心内占位",
        "IVC goes into RA": "下腔静脉进入右心房",
        "IVC size": "下腔静脉大小",
        "IVC valve, Eustachian valve": "下腔静脉瓣、Eustachian 瓣",
        "LA size": "左心房大小",
        "LA: size and volume": "左心房：大小和容积",
        "LA: size, volume": "左心房：大小、容积",
        "Lateral (L)": "侧壁（L）",
        "Left Atrial Appendage (LAA)*": "左心耳（LAA）*",
        "Left Atrium (LA)": "左心房（LA）",
        "Left atrium: size": "左心房：大小",
        "Left Common Carotid Artery (LCCA)": "左颈总动脉（LCCA）",
        "Left Coronary Cusp (LCC)": "左冠瓣尖（LCC）",
        "Left Innominate Vein": "左无名静脉",
        "Left Lower Pulmonary Vein (LLPV)": "左下肺静脉（LLPV）",
        "Left pleural effusion": "左侧胸腔积液",
        "Left pulmonary artery": "左肺动脉",
        "Left Pulmonary Artery (LPA)": "左肺动脉（LPA）",
        "Left Pulmonary Artery (LPA)*": "左肺动脉（LPA）*",
        "Left Subclavian Artery (LSA)": "左锁骨下动脉（LSA）",
        "Left Upper Pulmonary Vein (LUPV)*": "左上肺静脉（LUPV）*",
        "Left Ventricle (LV)": "左心室（LV）",
        "Left Ventricle (LV) walls": "左心室（LV）壁",
        "Left Ventricle (LV)*": "左心室（LV）*",
        "Left Ventricle (LV): apical segments": "左心室（LV）：心尖段",
        "Left Ventricle (LV): basal segments": "左心室（LV）：基底段",
        "Left Ventricular Outflow Tract (LVOT)": "左室流出道（LVOT）",
        "lengthen the IVS (rotate probe so marker at 2-3 o'clock)": "拉长室间隔（旋转探头，使标记指向 2-3 点钟方向）",
        "Liver": "肝脏",
        "look for liver surrounding both sides of IVC": "寻找包绕下腔静脉两侧的肝组织",
        "LV apex at the top of the display (slide probe)": "左心室心尖位于显示屏顶部（滑动探头）",
        "LV apex is thinner then the other LV walls and does not contract": "左心室心尖较其他左室壁薄，且不收缩",
        "LV function": "左心室功能",
        "LV function: global and segmental": "左心室功能：整体和节段",
        "LV function: global, segmental": "左心室功能：整体、节段",
        "LV: function (global and regional), aneurysm": "左心室：功能（整体和局部）、室壁瘤",
        "LV: size and function": "左心室：大小和功能",
        "LV: size and function, aneurysm": "左心室：大小和功能、室壁瘤",
        "LV: size, function (global, regional)": "左心室：大小、功能（整体、局部）",
        "LV: size, function and wall thickness": "左心室：大小、功能和壁厚",
        "LVOT alignment (higher interspace and slide probe lateral)": "左室流出道对齐（提高一个肋间隙并将探头向外侧滑动）",
        "LVOT obstruction": "左室流出道梗阻",
        "Main and Left Pulmonary Artery: size": "主肺动脉和左肺动脉：大小",
        "Main Pulmonary Artery": "主肺动脉",
        "Main Pulmonary Artery (MPA)": "主肺动脉（MPA）",
        "Main pulmonary artery: size, embolus": "主肺动脉：大小、栓子",
        "Main Pulmonary Artery: size, mass": "主肺动脉：大小、占位",
        "make the AV cusps appear symmetric (rotate probe)": "使主动脉瓣尖显示对称（旋转探头）",
        "make the IVC appear horizontal": "使下腔静脉呈水平显示",
        "make the IVS and posterior LV wall appear horizontal (change interspace)": "使室间隔和左室后壁呈水平显示（改变肋间隙）",
        "make the IVS appear vertical": "使室间隔呈垂直显示",
        "make the IVS appear vertical and in the center of the image": "使室间隔呈垂直并位于图像中央",
        "make the IVS appear vertical and in the center of the image (move probe laterally)": "使室间隔呈垂直并位于图像中央（探头向外侧移动）",
        "make the LV appear round in shape (change one interspace lower)": "使左心室呈圆形（下移一个肋间隙）",
        "make the LV appear round in shape (rotate probe)": "使左心室呈圆形（旋转探头）",
        "make the LV appear round in shape and the RV crescent shaped (change interspace)": "使左心室呈圆形、右心室呈新月形（改变肋间隙）",
        "make the LV appear round in shape and the RV crescent shaped (change one interspace lower)": "使左心室呈圆形、右心室呈新月形（下移一个肋间隙）",
        "make the main pulmonary artery walls appear symmetric (rotate probe)": "使主肺动脉壁显示对称（旋转探头）",
        "make the PV cusps appear symmetric (rotate probe clockwise)": "使肺动脉瓣尖显示对称（顺时针旋转探头）",
        "make the TV cusps appear symmetric (rotate probe clockwise)": "使三尖瓣瓣叶显示对称（顺时针旋转探头）",
        "-measure 0.5-3.0cm from RA junction": "-从右心房交界处测量 0.5-3.0 cm",
        "Mitral Valve": "二尖瓣",
        "Mitral Valve (MV)": "二尖瓣（MV）",
        "Mitral Valve (MV)*": "二尖瓣（MV）*",
        "Mitral Valve (MV):": "二尖瓣（MV）：",
        "Mitral valve:": "二尖瓣：",
        "Mitral Valve:": "二尖瓣：",
        "Mitral valve: structure": "二尖瓣：结构",
        "Mitral Valve: structure and function": "二尖瓣：结构和功能",
        "modification of the Apical 2 Chamber view": "心尖两腔心切面的变体",
        "modification of the Apical 4 Chamber view": "心尖四腔心切面的变体",
        "modification of the Parasternal LAX view": "胸骨旁长轴切面的变体",
        "modification of the Parasternal LAX view in which the AV is in the center of the screen": "胸骨旁长轴切面的变体，使主动脉瓣位于屏幕中央",
        "modification of the Parasternal SAX AV and RVOT Level view": "胸骨旁短轴主动脉瓣及右室流出道水平切面的变体",
        "modification of the subcostal 4C view": "剑突下四腔心切面的变体",
        "move the probe one interspace higher to image the Ascending Aorta in LAX": "将探头上移一个肋间隙，以长轴显示升主动脉",
        "no change in aorta size with respiration": "主动脉大小不随呼吸变化",
        "no papillary muscles should be seen (tilt or slide inferior)": "不应看到乳头肌（向下倾斜或滑动）",
        "no papillary muscles should be seen (tilt probe)": "不应看到乳头肌（倾斜探头）",
        "Non coronary cusp (NCC)": "无冠瓣尖（NCC）",
        "Non-coronary Cusp (NCC)": "无冠瓣尖（NCC）",
        "non-pulsatile IVC, pulsatility of aorta": "下腔静脉无搏动，主动脉有搏动",
        "-normal ≤2.1cm": "-正常 ≤2.1 cm",
        "not foreshorten the LV apex (slide probe to apex)": "不要缩短左心室心尖（将探头滑向心尖）",
        "not visualize the AV (if AV seen then tilt probe posterior or rotate the probe)": "不要显示主动脉瓣（若看到主动脉瓣，则向后倾斜或旋转探头）",
        "not visualize the mitral valve (tilt more inferior or change one interspace lower)": "不要显示二尖瓣（进一步向下倾斜或下移一个肋间隙）",
        "not visulaize the AV (if AV is seen the probe is too anterior, tilt probe posterior)": "不要显示主动脉瓣（若看到主动脉瓣，说明探头过于靠前，应向后倾斜）",
        "open the lumen of the aorta and see arch (rotate probe)": "打开主动脉管腔并显示主动脉弓（旋转探头）",
        "Origin of head vessels (LCCA, LSCA)": "头臂血管起源（LCCA、LSCA）",
        "Pacer wires": "起搏器导线",
        "Patent ductus arteriosus (PDA)": "动脉导管未闭（PDA）",
        "Patent Ductus Arteriosus (PDA)": "动脉导管未闭（PDA）",
        "-patient to sniff for IVC collapse": "-让患者快速吸气以观察下腔静脉塌陷",
        "Pericardial effusion": "心包积液",
        "-perpendicular to IVC long axis": "-垂直于下腔静脉长轴",
        "place the LV in the center of the image (rotate probe)": "将左心室置于图像中央（旋转探头）",
        "place the LV in the center of the image (slide probe)": "将左心室置于图像中央（滑动探头）",
        "place the MV and AV in the center of the image (tilt probe away from sternum)": "将二尖瓣和主动脉瓣置于图像中央（探头远离胸骨方向倾斜）",
        "Position the TTE transducer:": "放置 TTE 探头：",
        "Posterior Mitral Valve leaflet (PMVL)": "二尖瓣后叶（PMVL）",
        "Posterior Mitral Valve Leaflet (PMVL)": "二尖瓣后叶（PMVL）",
        "Posterior Tricuspid Valve Leaflet (PTVL)": "三尖瓣后叶（PTVL）",
        "Posteromedial Papillary Muscle (PM)": "后内侧乳头肌（PM）",
        "Pulmonary embolism": "肺栓塞",
        "Pulmonic Valve (PV)": "肺动脉瓣（PV）",
        "Pulmonic Valve: structure and function": "肺动脉瓣：结构和功能",
        "RA and LA size": "右心房和左心房大小",
        "RA: size": "右心房：大小",
        "-record several beats": "-记录数个心动周期",
        "Right Atrium (RA)": "右心房（RA）",
        "Right Atrium: size": "右心房：大小",
        "Right Brachiocephalic Artery (RBCA)": "右头臂动脉（RBCA）",
        "Right Coronary Cusp (RCC)": "右冠瓣尖（RCC）",
        "Right heart should not be seen (not enough probe rotation)": "不应看到右心（探头旋转不足）",
        "Right Pulmonary Artery (RPA)": "右肺动脉（RPA）",
        "Right pulmonary Artery (RPA)": "右肺动脉（RPA）",
        "Right Pulmonary Artery (RPA)*": "右肺动脉（RPA）*",
        "Right Pulmonary Artery: dilatation, embolus": "右肺动脉：扩张、栓子",
        "Right Upper Pulmonary Vein (RUPV)": "右上肺静脉（RUPV）",
        "Right Ventricle (RV)": "右心室（RV）",
        "Right Ventricle (RV) apex": "右心室（RV）心尖",
        "Right Ventricular Outflow Tract (RVOT)": "右室流出道（RVOT）",
        "Right Ventricular Outflow Tract: size": "右室流出道：大小",
        "Right Ventricular Outflow Tract: size, obstruction": "右室流出道：大小、梗阻",
        "rotate the probe 90° clockwise from the right shoulder (marker at 11 o'clock) so the index marker now points towards the left shoulder (2 o'clock)": "从指向右肩（11 点钟方向）开始，将探头顺时针旋转 90 度，使标记指向左肩（2 点钟方向）",
        "RV free wall or Anterolateral (AL)": "右心室游离壁或前外侧壁（AL）",
        "RV function": "右心室功能",
        "RV: size and function": "右心室：大小和功能",
        "RV: size and function, wires": "右心室：大小和功能、导线",
        "RV: size, function, wall thickness": "右心室：大小、功能、壁厚",
        "RVOT: size, obstruction": "右室流出道：大小、梗阻",
        "see entire LV including apex (slide probe)": "显示包括心尖在内的整个左心室（滑动探头）",
        "Septal (S)": "间隔（S）",
        "Septal Tricuspid Valve Leaflet (STVL)": "三尖瓣隔叶（STVL）",
        "Septal Tricuspid Valve leaflet (STVL)": "三尖瓣隔叶（STVL）",
        "Septal Triscuspid Valve Leaflet (STVL)": "三尖瓣隔叶（STVL）",
        "Similar to Parasternal SAX at Apex": "类似胸骨旁短轴心尖水平",
        "Similar to Parasternal SAX LV at Mid Level": "类似胸骨旁短轴左心室中段水平",
        "Similar to Parasternal SAX LV at Mitral Valve Level": "类似胸骨旁短轴左心室二尖瓣水平",
        "slightly tilted inferiorly towards LV apex": "稍向下倾斜，朝向左心室心尖",
        "Superior Vena Cava (SVC)": "上腔静脉（SVC）",
        "tilt anterior to see the aortic valve": "向前倾斜以显示主动脉瓣",
        "tilt inferior and anterior": "向下并向前倾斜",
        "tilt or slide inferiorly towards LV apex": "向左心室心尖方向向下倾斜或滑动",
        "tilt to the patient's left": "向患者左侧倾斜",
        "tilted inferiorly and medially (towards R hip)": "向下内侧倾斜（朝向右髋）",
        "tilted superiorly and laterally (L shoulder)": "向上外侧倾斜（朝向左肩）",
        "tilted superiorly and medially": "向上内侧倾斜",
        "Tricuspid valve": "三尖瓣",
        "Tricuspid Valve": "三尖瓣",
        "Tricuspid Valve (TV)": "三尖瓣（TV）",
        "Tricuspid Valve (TV)*": "三尖瓣（TV）*",
        "Tricuspid Valve: structure and function": "三尖瓣：结构和功能",
        "turn 90° counterclockwise to see the Ascending Aorta in SAX": "逆时针旋转 90 度，以短轴显示升主动脉",
        "turn the probe towards the patient's right (more midline)": "将探头转向患者右侧（更靠近中线）",
        "-use m-mode": "-使用 M 型超声",
        "Ventricular septal defect": "室间隔缺损",
        "Ventricular Septal Defect (VSD)": "室间隔缺损（VSD）",
        "view all four cardiac chambers": "显示四个心腔",
        "view the descending aorta (tilt more anterior)": "显示降主动脉（进一步向前倾斜）",
        "view the head vessels (tilt more posterior)": "显示头臂血管（进一步向后倾斜）",
        "view the junction of the IVC and RA (IVC must be shown to enter the RA)": "显示下腔静脉与右心房交界处（必须显示下腔静脉进入右心房）",
        "visualize aortic valve cusps": "显示主动脉瓣尖",
        "visualize both mitral valve leaflets (tilt or slide probe inferior)": "显示二尖瓣前后叶（探头向下倾斜或滑动）",
        "visualize both papillary muscles attached to the LV wall (change one interspace lower)": "显示附着于左室壁的两组乳头肌（下移一个肋间隙）",
        "visualize both papillary muscles attached to the LV wall (tilt probe)": "显示附着于左室壁的两组乳头肌（倾斜探头）",
        "visualize only the RV and not the LV": "只显示右心室，不显示左心室",
        "visualize the Aortic Valve (tilt probe towards midline)": "显示主动脉瓣（探头向中线倾斜）",
        "Visualize the ascending aorta": "显示升主动脉",
        "visualize the AV and LVOT (rotate probe)": "显示主动脉瓣和左室流出道（旋转探头）",
        "visualize the AV and LVOT (tilt probe anterior)": "显示主动脉瓣和左室流出道（探头向前倾斜）",
        "visualize the endocardium": "显示心内膜",
        "visualize the mitral valve (tilt probe)": "显示二尖瓣（倾斜探头）",
        "visualize the RV apex (change one interspace lower)": "显示右心室心尖（下移一个肋间隙）",
        "visualize the RV outflow tract (change one interspace higher)": "显示右室流出道（上移一个肋间隙）",
        "visualize valvular leaflets": "显示瓣叶",
        "with the index marker now pointing towards the head (12 o'clock)": "此时标记指向头侧（12 点钟方向）",
        "with the index marker now pointing towards the left axilla (1 o'clock)": "此时标记指向左腋窝（1 点钟方向）",
        "with the index marker now pointing towards the right shoulder (11 o'clock)": "此时标记指向右肩（11 点钟方向）",
        "with the index marker pointing towards the head (12 o'clock)": "标记指向头侧（12 点钟方向）",
        "with the index marker pointing towards the left (3 o'clock)": "标记指向左侧（3 点钟方向）",
        "with the index marker pointing towards the left clavicle (1 o'clock)": "标记指向左锁骨（1 点钟方向）",
        "with the index marker pointing towards the left shoulder (1-2 o'clock)": "标记指向左肩（1-2 点钟方向）",
        "with the index marker pointing towards the left shoulder (2 o'clock)": "标记指向左肩（2 点钟方向）",
        "with the index marker pointing towards the left supraclavicular notch (1 o'clock)": "标记指向左锁骨上窝（1 点钟方向）",
        "with the index marker pointing towards the right shoulder (11 o'clock)": "标记指向右肩（11 点钟方向）"
    };

    var fallbackTerms = [
        ["Right Ventricular Outflow Tract", "右室流出道"],
        ["Left Ventricular Outflow Tract", "左室流出道"],
        ["Interventricular Septum", "室间隔"],
        ["Inter-ventricular Septum", "室间隔"],
        ["Interatrial Septum", "房间隔"],
        ["Inter-atrial Septum", "房间隔"],
        ["Inferior Vena Cava", "下腔静脉"],
        ["Superior Vena Cava", "上腔静脉"],
        ["Ascending Aorta", "升主动脉"],
        ["Descending Aorta", "降主动脉"],
        ["Aortic Valve", "主动脉瓣"],
        ["Mitral Valve", "二尖瓣"],
        ["Tricuspid Valve", "三尖瓣"],
        ["Pulmonic Valve", "肺动脉瓣"],
        ["Pulmonary Artery", "肺动脉"],
        ["Left Atrium", "左心房"],
        ["Right Atrium", "右心房"],
        ["Left Ventricle", "左心室"],
        ["Right Ventricle", "右心室"],
        ["Coronary Sinus", "冠状静脉窦"],
        ["Pericardial effusion", "心包积液"],
        ["Left pleural effusion", "左侧胸腔积液"],
        ["Atrial septal defect", "房间隔缺损"],
        ["Ventricular septal defect", "室间隔缺损"],
        ["function", "功能"],
        ["size", "大小"],
        ["structure", "结构"],
        ["obstruction", "梗阻"],
        ["aneurysm", "动脉瘤"],
        ["dissection", "夹层"],
        ["dilation", "扩张"],
        ["volume", "容积"],
        ["wall thickness", "壁厚"]
    ];

    function normalizeDetailText(text) {
        return String(text)
            .replace(/\s+/g, " ")
            .replace(/掳/g, "°")
            .replace(/鈮\?/g, "≤")
            .replace(/鈮/g, "≤")
            .trim();
    }

    function escapeRegExp(text) {
        return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    }

    function fallbackTranslate(source) {
        var result = source;

        fallbackTerms.forEach(function(pair) {
            result = result.replace(new RegExp(escapeRegExp(pair[0]), "g"), pair[1]);
        });

        return result;
    }

    function translateTextValue(value) {
        var source = normalizeDetailText(value);

        if (!source) {
            return value;
        }

        var translated = exactTranslations[source] || fallbackTranslate(source);
        var leading = String(value).match(/^\s*/)[0];
        var trailing = String(value).match(/\s*$/)[0];

        return leading + translated + trailing;
    }

    function translateElementTextNodes(element) {
        var walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT, null, false);
        var nodes = [];
        var node;

        while ((node = walker.nextNode())) {
            nodes.push(node);
        }

        nodes.forEach(function(textNode) {
            textNode.nodeValue = translateTextValue(textNode.nodeValue);
        });
    }

    window.tteDetailTranslationsZh = exactTranslations;
    window.tteNormalizeDetailText = normalizeDetailText;
    window.tteTranslateDetailHtml = function(html) {
        var container = document.createElement("div");
        container.innerHTML = html || "";
        translateElementTextNodes(container);
        return container.innerHTML;
    };
})(window);
